name: 'Ansible Linting'

on:
  pull_request:
    branches:
      - main
      - dev
    paths:
      - '.github/ansible/**'

env:
  ANSIBLE_CONFIG: .github/ansible/ansible.cfg

jobs:
  ansible-lint:
    name: Ansible Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run ansible-lint
        shell: bash
        run: ansible-lint -v -p .github/ansible/**/*
